import XCTest
@testable import MindoModel

final class AsciiDocExporterTests: XCTestCase {

    func testEmptyMapEmitsHeaderOnly() {
        let out = AsciiDocExporter.export(MindMap())
        XCTAssertTrue(out.hasPrefix("// Generated by Mindo"))
    }

    func testRootIsLevelOneEqualsChildrenIncrease() {
        let map = MindMap()
        let root = Topic(text: "Root"); map.root = root
        let a = root.addChild(text: "Alpha")
        _ = a.addChild(text: "A1")
        _ = root.addChild(text: "Beta")

        let out = AsciiDocExporter.export(map)
        XCTAssertTrue(out.contains("\n= Root\n"))
        XCTAssertTrue(out.contains("\n== Alpha\n"))
        XCTAssertTrue(out.contains("\n=== A1\n"))
        XCTAssertTrue(out.contains("\n== Beta\n"))
    }

    func testRootGetsEncodingAttribute() {
        let map = MindMap()
        map.root = Topic(text: "Root")
        let out = AsciiDocExporter.export(map)
        XCTAssertTrue(out.contains(":encoding: UTF-8"))
    }

    func testHeadingNewlineBecomesPassthroughBr() {
        // AsciiDoc headings end at \n — must collapse to pass:[<br>].
        XCTAssertEqual(
            AsciiDocExporter.escapeHeading("two\nlines"),
            "two pass:[<br>]lines"
        )
    }

    func testHeadingDropsControlCharacters() {
        XCTAssertEqual(AsciiDocExporter.escapeHeading("clean\u{07}text"), "cleantext")
    }

    func testNoteEmittedAsHardBreakLines() {
        let map = MindMap()
        let root = Topic(text: "Root"); map.root = root
        root.setExtra(ExtraNote(text: "first\nsecond"))
        let out = AsciiDocExporter.export(map)
        XCTAssertTrue(out.contains("first +\n"))
        XCTAssertTrue(out.contains("second +\n"))
    }

    func testLinkAndFileExtras() {
        let map = MindMap()
        let root = Topic(text: "Root"); map.root = root
        root.setExtra(ExtraLink(uri: "https://example.com"))
        root.setExtra(ExtraFile(uri: "/tmp/foo.txt"))
        let out = AsciiDocExporter.export(map)
        XCTAssertTrue(out.contains("link:https://example.com[Link]"))
        XCTAssertTrue(out.contains("link:++/tmp/foo.txt++[File]"))
    }

    func testCodeSnippetsEmittedAsSourceBlocks() {
        let map = MindMap()
        let root = Topic(text: "Root"); map.root = root
        root.putCodeSnippet(language: "swift", body: "let x = 1\n")
        let out = AsciiDocExporter.export(map)
        XCTAssertTrue(out.contains("[source,swift]\n----\nlet x = 1\n----\n"))
    }

    func testCodeSnippetSortedByLanguageForStableOutput() {
        let map = MindMap()
        let root = Topic(text: "Root"); map.root = root
        root.putCodeSnippet(language: "swift", body: "let s = 1\n")
        root.putCodeSnippet(language: "go",    body: "x := 1\n")
        let out = AsciiDocExporter.export(map)
        let goRange = out.range(of: "[source,go]")!
        let swiftRange = out.range(of: "[source,swift]")!
        XCTAssertLessThan(goRange.lowerBound, swiftRange.lowerBound)
    }
}
