import XCTest
@testable import MindoModel

/// Tests that print the lexer's token stream for small inputs. Used to chase parsing bugs.
final class LexerDebugTests: XCTestCase {

    func testTokenStreamOnSimpleMap() {
        let text = """
        Mind Map generated by Mindolph
        > __version__=`1.1`
        ---

        # Root

        ## Summary

        ## Features

        ### Outline view\\.

        """
        var lexer = MmdLexer(buffer: text)
        var tokens: [(String, String)] = []
        var safety = 0
        while safety < 100 {
            let oldOffset = lexer.offset
            lexer.advance()
            if lexer.offset == oldOffset || lexer.tokenType == nil { break }
            tokens.append(("\(lexer.tokenType!)", lexer.tokenText))
            safety += 1
        }
        for t in tokens {
            print("TOK \(t.0)\t\(t.1.debugDescription)")
        }
        // Only succeeds if our parsing reaches end of input.
        XCTAssertGreaterThan(tokens.count, 8, "expected at least header + 4 topics worth of tokens")
        // Sanity: should see HEAD_DELIMITER and several TOPIC_TITLE tokens.
        XCTAssertTrue(tokens.contains { $0.0 == "headDelimiter" })
        let titles = tokens.filter { $0.0 == "topicTitle" }
        XCTAssertEqual(titles.count, 4)
    }
}
