import Foundation

/// Emits a mindmap as AsciiDoc text. Mirrors mindolph's
/// `ASCIIDocExporter` / `AsciiDocBranchExporter`:
/// - heading depth uses `=` repetition (`=`, `==`, `===`, …)
/// - root prints a `:encoding: UTF-8` attribute block
/// - notes → ` +` line breaks (AsciiDoc's hard break)
/// - link/file → `link:URL[Label]`
/// - code snippets → `[source,lang]` + `----` fenced blocks
///
/// Embedded newlines in topic text become AsciiDoc's `pass:[<br>]`
/// passthrough so a heading stays on one line.
public enum AsciiDocExporter {

    public static func export(_ map: MindMap) -> String {
        var out = ""
        out.append("// Generated by Mindo AsciiDoc exporter\n")
        if let root = map.root {
            writeTopic(root, level: 0, into: &out)
        }
        return out
    }

    private static func writeTopic(_ topic: Topic, level: Int, into out: inout String) {
        let prefix = String(repeating: "=", count: level + 1)
        out.append("\(prefix) \(escapeHeading(topic.text))\n")

        if level == 0 {
            out.append(":encoding: UTF-8\n")
        }
        out.append("\n")

        if let note = topic.extra(.note) as? ExtraNote, !note.text.isEmpty {
            for line in note.text.split(separator: "\n", omittingEmptySubsequences: false) {
                out.append("\(line) +\n")
            }
            out.append("\n")
        }
        if let file = topic.extra(.file) as? ExtraFile, !file.uri.isEmpty {
            // `++uri++` passthrough so URIs with `[]` chars don't break
            // AsciiDoc's link macro parser.
            out.append("link:++\(file.uri)++[File]\n\n")
        }
        if let link = topic.extra(.link) as? ExtraLink, !link.uri.isEmpty {
            out.append("link:\(link.uri)[Link]\n\n")
        }

        let sortedLangs = topic.codeSnippets.keys.sorted()
        for lang in sortedLangs {
            guard let body = topic.codeSnippets[lang] else { continue }
            out.append("[source,\(lang)]\n----\n")
            out.append(body)
            if !body.hasSuffix("\n") { out.append("\n") }
            out.append("----\n\n")
        }

        for child in topic.children {
            writeTopic(child, level: level + 1, into: &out)
        }
    }

    /// AsciiDoc headings end at \n — replace embedded newlines with the
    /// `pass:[<br>]` passthrough that mindolph uses, drop control chars.
    static func escapeHeading(_ s: String) -> String {
        var out = ""
        out.reserveCapacity(s.count)
        for ch in s {
            if ch == "\n" || ch == "\r" { out.append(" pass:[<br>]"); continue }
            if let scalar = ch.unicodeScalars.first, CharacterSet.controlCharacters.contains(scalar) { continue }
            out.append(ch)
        }
        return out
    }
}
