import Foundation

public enum MmdConstants {
    public static let nextLine = "\n"
    public static let nextParagraph = "   \n"
    public static let dateTimeFormat = "yyyy-MM-dd HH:mm:ss"

    public static let formatVersion = "1.1"
    public static let generatorVersionAttr = "__version__"

    public static let generatorHeader = "Mind Map generated by Mindolph"
}
