import XCTest
@testable import KepModel

final class MindMapRoundTripTests: XCTestCase {

    /// Build a small mind map programmatically, write it, parse it back, and assert structure.
    func testProgrammaticBuildRoundTrip() throws {
        let map = MindMap()
        let root = Topic(text: "Root")
        map.root = root
        let summary = root.addChild(text: "Summary")
        summary.setAttribute(TopicAttribute.emoticon, "comment")
        summary.setExtra(ExtraNote(text: "First sentence.\nSecond."))

        let features = root.addChild(text: "Features")
        let bullet = features.addChild(text: "Outline view (with . dot)")
        bullet.setExtra(ExtraLink(uri: "https://github.com/mindolph/Mindolph"))

        let serialized = map.write()
        XCTAssertTrue(serialized.contains("Mind Map generated by Mindolph"))
        XCTAssertTrue(serialized.contains("# Root"))
        XCTAssertTrue(serialized.contains("## Summary"))

        let parsed = try MindMap(text: serialized)
        XCTAssertNotNil(parsed.root)
        XCTAssertEqual(parsed.root?.text, "Root")
        XCTAssertEqual(parsed.root?.children.count, 2)

        let parsedSummary = parsed.root?.children.first
        XCTAssertEqual(parsedSummary?.text, "Summary")
        XCTAssertEqual(parsedSummary?.attribute(TopicAttribute.emoticon), "comment")
        let note = parsedSummary?.extra(.note) as? ExtraNote
        XCTAssertEqual(note?.text, "First sentence.\nSecond.")

        let parsedFeatures = parsed.root?.children.last
        XCTAssertEqual(parsedFeatures?.children.count, 1)
        let parsedBullet = parsedFeatures?.children.first
        XCTAssertEqual(parsedBullet?.text, "Outline view (with . dot)")
        let link = parsedBullet?.extra(.link) as? ExtraLink
        XCTAssertEqual(link?.uri, "https://github.com/mindolph/Mindolph")
    }

    /// Parse the real-world Mindolph fixture and re-serialize it; the second round-trip must match the first.
    func testDemoFixtureStableUnderRoundTrip() throws {
        let url = try fixtureURL(named: "DemoMindMap.mmd")
        let original = try String(contentsOf: url, encoding: .utf8)

        let parsed = try MindMap(text: original)
        XCTAssertNotNil(parsed.root, "expected a root topic in the demo fixture")

        // Stable round-trip: writing twice should be deterministic.
        let firstWrite = parsed.write()
        let secondParsed = try MindMap(text: firstWrite)
        let secondWrite = secondParsed.write()
        XCTAssertEqual(firstWrite, secondWrite, "mmd write should be idempotent under reparse")

        // Sanity: a known topic title from the fixture should survive.
        var seenSummary = false
        var seenFeatures = false
        var seenLLMNote = false
        parsed.root?.traverse { topic in
            if topic.text == "Summary" { seenSummary = true }
            if topic.text == "Features" { seenFeatures = true }
            if let note = topic.extra(.note) as? ExtraNote,
               note.text.contains("Supported LLM providers") {
                seenLLMNote = true
            }
        }
        XCTAssertTrue(seenSummary, "fixture should contain a 'Summary' topic")
        XCTAssertTrue(seenFeatures, "fixture should contain a 'Features' topic")
        XCTAssertTrue(seenLLMNote, "fixture should contain the LLM-providers note")
    }

    /// Diagnostic — prints how many topics & what extras the demo fixture parsed into.
    /// Useful when iterating on the parser; never fails by itself.
    func testDemoFixtureStats() throws {
        let url = try fixtureURL(named: "DemoMindMap.mmd")
        let text = try String(contentsOf: url, encoding: .utf8)
        let parsed = try MindMap(text: text)
        let total = parsed.root?.subtreeCount() ?? 0
        XCTAssertGreaterThan(total, 30, "demo fixture should contain a non-trivial number of topics")
    }

    /// The snapshot-undo mechanism used for Lua/agent runs: write() a snapshot,
    /// mutate the map in place, then restore the snapshot by swapping root +
    /// reattaching the map backref across the tree. Restoring `before` must
    /// reproduce the original serialization exactly, and leave the live `map`
    /// reference usable (every topic.map points back at it).
    func testSnapshotRestoreRoundTrip() throws {
        let map = MindMap()
        let root = Topic(text: "Root")
        map.root = root
        let a = root.addChild(text: "Alpha")
        _ = a.addChild(text: "A1")
        _ = root.addChild(text: "Beta")

        let before = map.write()

        // Mutate in place (as a script would): rename, add, remove.
        a.text = "Alpha renamed"
        _ = a.addChild(text: "A2")
        if let beta = root.children.last { root.removeChild(beta) }
        XCTAssertNotEqual(map.write(), before, "precondition: the mutation changed the map")

        // Restore — the exact logic in AppSession.registerMapSnapshotUndo.
        func restore(_ mmd: String) throws {
            let parsed = try MindMap(text: mmd)
            map.root = parsed.root
            map.root?.traverse { $0.map = map }
        }
        try restore(before)

        XCTAssertEqual(map.write(), before, "restoring the snapshot must reproduce the original exactly")
        XCTAssertEqual(map.root?.children.map(\.text), ["Alpha", "Beta"])
        // Backref reattached across the whole tree → further edits stay consistent.
        var allReattached = true
        map.root?.traverse { if $0.map !== map { allReattached = false } }
        XCTAssertTrue(allReattached, "every topic.map must point back at the live map")
    }

    // MARK: - Helpers

    private func fixtureURL(named name: String) throws -> URL {
        let bundle = Bundle.module
        guard let url = bundle.url(forResource: name, withExtension: nil, subdirectory: "Fixtures")
            ?? bundle.url(forResource: name.replacingOccurrences(of: ".mmd", with: ""), withExtension: "mmd", subdirectory: "Fixtures")
            ?? bundle.url(forResource: name, withExtension: nil)
        else {
            throw XCTSkip("fixture \(name) not found in test bundle")
        }
        return url
    }
}
